@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJyc3pjemVwYW5za2kiLCJmaXJzdE5hbWUiOiJSYWRvc8WCYXciLCJsYXN0TmFtZSI6IlN6Y3plcGHFhHNraSIsImF1dGhvcml0eSI6Ik1PREVSQVRPUiIsImlhdCI6MTY0NzAzMzEwNSwiZXhwIjoxNjQ3MDM0MDA1fQ.5J5n2shGNY33DrEQscgxqYurBZYIC3bdUxW6www6mB4

// AUTH controller
POST http://localhost:3000/client/auth/login HTTP/1.1
content-type: application/json
x-custom-lang: pl

{
    "email": "r.szczepanski02@gmail.com",
    "password": "admin"
}
###
POST http://localhost:3000/client/auth/register HTTP/1.1
content-type: application/json
x-custom-lang: pl

{
    "username": "rszczepanski2",
    "password": "admin",
    "firstName": "Radosław",
    "lastName": "Szczepański",
    "email": "r.szczepanski022@gmail.com",
    "lang": "pl",
    "accountType": "CLIENT",
    "age": 20,
    "gender": "MALE",
    "country": "Poland",
    "city": "Cracow",
    "zipCode": 32064
}

###
DELETE http://localhost:3000/client/auth/refreshToken/86 HTTP/1.1



// GOOGLE STRATEGY
###
GET http://localhost:3000/client/auth/auth-google HTTP/1.1
